=== pkesel/integration/reference/domain-model/src/main/resources/account.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.catalina.com/account"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:hj="http://hyperjaxb3.jvnet.org/ejb/schemas/customizations"
	xmlns:acct="http://www.catalina.com/account">
	<xs:complexType name="Client">
		<xs:annotation>
			<xs:appinfo>
				<hj:embeddable />
			</xs:appinfo>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="clientName" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="Contract">
		<xs:annotation>
			<xs:appinfo>
				<hj:embeddable />
			</xs:appinfo>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="clientId" type="xs:int"></xs:element>
			<xs:element name="createDate" type="xs:dateTime"></xs:element>
			<xs:element name="effectiveDate" type="xs:dateTime"></xs:element>
			<xs:element name="expirationDate" type="xs:dateTime"></xs:element>
			<xs:element name="contractTerms" type="xs:string"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"></xs:attribute>
	</xs:complexType>
	<xs:complexType name="Account">
		<xs:sequence>
			<xs:element name="client" type="acct:Client" minOccurs="1"
				maxOccurs="1"></xs:element>
			<xs:element name="contract" type="acct:Contract"
				minOccurs="0" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int"></xs:attribute>
	</xs:complexType>
	<xs:element name="client" type="acct:Client"></xs:element>
	<xs:element name="account" type="acct:Account"></xs:element>
</xs:schema>

=== pkesel/integration/reference/domain-model/src/test/resources/accountExample2.xml
<?xml version="1.0" encoding="UTF-8"?>
<acct:account id="1" xmlns:acct="http://www.catalina.com/account"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.catalina.com/account ../../main/resources/account.xsd ">
	<acct:client id="1">
		<acct:clientName>Client 1</acct:clientName>
	</acct:client>
	<acct:contract id="1">
		<acct:clientId>1</acct:clientId>
		<acct:createDate>2014-03-10T12:00:00</acct:createDate>
		<acct:effectiveDate>2014-04-01T12:00:00</acct:effectiveDate>
		<acct:expirationDate>2014-05-31T12:00:00</acct:expirationDate>
		<acct:contractTerms>Some contract terms about payment, execution,
			guarantee, liability, yada, yada, etc.</acct:contractTerms>
	</acct:contract>
	<acct:contract id="2">
		<acct:clientId>1</acct:clientId>
		<acct:createDate>2014-09-10T12:00:00</acct:createDate>
		<acct:effectiveDate>2014-10-01T12:00:00</acct:effectiveDate>
		<acct:expirationDate>2014-12-31T12:00:00</acct:expirationDate>
		<acct:contractTerms>Some contract terms about payment, execution,
			guarantee, liability, yada, yada, etc.</acct:contractTerms>
	</acct:contract>
</acct:account>
